### ISSUE TITLE
Need help in setting it up as a beginner step by step

### ISSUE THREAD

**Issue by alisiddiqui1987** [studiomotio/zeroclick#11]
Hi Xavier,

Can you please help setting it up step by step guide. I am pretty new to linux and its tools and I am not a programmer.

Thanks

**Comment by xavierfoucrier** [comment]
Hello @alisiddiqui1987 👋 

This is not an issue related to this plugin.

Please write down to me on my private email here:
https://xavierfoucrier.dev/

Thanks a lot 😉
